### PR TITLE
add junopunks nft dapp

### PR DESCRIPTION
**Pull request by wrjanan**

### CODE REVIEW

**Comment by blockcreators** [comment]
Is project live on mainnet?

**Comment by wrjanan** [comment]
@blockcreators 
Yes it is live on mainnet.

**Comment by wrjanan** [comment]
Hello~

This project is live on mainnet, for the mint, you have to connect before the mint button shows.
https://junopunks.io/

Is there any concerns?

**Comment by blockcreators** [comment]
> Hello~
> 
> This project is live on mainnet, for the mint, you have to connect before the mint button shows. https://junopunks.io/
> 
> Is there any concerns?

Please add the contract address

**Comment by wrjanan** [comment]
eh? is this specific for junopunks? how come other projects like junoswap junoscan do not need to have contract address?

**Comment by wrjanan** [comment]
I assume that the address field is meant for contract address?
Is this the right field? or should I create a separate field called contract_address?

**Comment by wrjanan** [comment]
I added another project meant to be a decentralised listing for NFTs of Juno https://hippietechies.github.io/nftjuno/
Have merged with master and ended up with other commits as part of this PR, if it is too confusing, I will make a new PRs for 2 different PRs.

Else, there are 2 new projects in this PR:
1) JunoPunks
- added contract address as per review

2) NFTs on Juno
- add website and github link

**Comment by wrjanan** [comment]
@blockcreators

**Comment by nullmames** [comment]
please resubmit if still required

**Pull request closed without merging**
