### PR TITLE
Add Cannalabs to the Juno projects list

### PR DESCRIPTION
**Pull request by seekingtau**
This is a pull request to add Cannalabs to the Juno projects list.

### CODE REVIEW

**Comment by blockcreators** [comment]
> This is a pull request to add Cannalabs to the Juno projects list.

Image size must be 120x120

**Comment by seekingtau** [comment]
fixing image size now - thank you!

**Comment by seekingtau** [comment]
just updated

**Comment by seekingtau** [comment]
just updated, redid it so it should be good, image is now 120x120

**Pull request merged**
