### PR TITLE
Change logo of Sputnik

### PR DESCRIPTION
**Pull request by Antropocosmist**
from image.png to sputnik512.png

### CODE REVIEW

**Review by giansalex — APPROVED** [review]

**Comment by nullmames** [comment]
LGTM

**Comment by giansalex** [comment]
This repo needs github actions for auto-deploy

**Comment by nullmames** [comment]
Actually, the image needs to be renamed to `image.png` as per the telegram-price-bot index.json configuration. I dont see an update to https://github.com/CosmosContracts/website/blob/main/projects/telegram-price-bot/index.json with the PR.

**Review by nullmames — CHANGES_REQUESTED** [review]
change name of logo to image.png, or update index.json

**Comment by nullmames** [comment]
LGTM

**Review by nullmames — APPROVED** [review]

**Pull request closed without merging**
