### PR TITLE
add cosmos-gov

### PR DESCRIPTION
**Pull request by shifty11**
Add Cosmos-Gov
A Telegram bot that tracks governance proposals of Juno and other Cosmos based chains

### CODE REVIEW

**Comment by blockcreators** [comment]
Should be 'Tools' not 'Tool'

**Comment by shifty11** [comment]
Okay, changed it

**Comment by blockcreators** [comment]
If the telegram group mods decide to add it, then we can add it to the ecosystem.

**Comment by nullmames** [comment]
please resubmit if still required

**Pull request closed without merging**
