### PR TITLE
Modify Ecosystem Page

### PR DESCRIPTION
**Pull request by CosmosCamel**
- Add Soon tab
- Remove Contracts from All and added Soon
- Show all Contract category under Contracts
- Show text for all other than featured only

Please review, edit if needed, and merge.
Thanks

### CODE REVIEW

**Comment by nullmames** [comment]
Hi @CamelJuno. 

Did we agree to remove the featured? what is your reasoning for this.

Given that the "Soon" page could quite potentially have nothing it it as some stage, should we put a condition to have a place holder like "Lets get building" or something like this rather than a blank page?

Null.

**Comment by CamelJuno** [comment]
> 

The featured aren't removed. Only the condition which shows text if featured is adjusted to show text for all where text exists.

I've added conditional render for the soon page so a placeholder will appear if none exist.

**Comment by CamelJuno** [comment]
> Hi @CamelJuno.
> 
> Did we agree to remove the featured? what is your reasoning for this.
> 
> Given that the "Soon" page could quite potentially have nothing it it as some stage, should we put a condition to have a place holder like "Lets get building" or something like this rather than a blank page?
> 
> Null.

The featured aren't removed. Only the condition which shows text if featured is adjusted to show text for all where text exists.

Great idea pointing out if Soon page is blank.

I've added conditional render for the soon page so a placeholder will appear if none exist in the recent commit.

**Comment by CosmosCamel** [comment]
> Hi @CamelJuno.
> 
> Did we agree to remove the featured? what is your reasoning for this.
> 
> Given that the "Soon" page could quite potentially have nothing it it as some stage, should we put a condition to have a place holder like "Lets get building" or something like this rather than a blank page?
> 
> Null.

Hi @nullmames 

The featured aren't removed. Only the condition which shows text if featured is adjusted to show text for all where text exists.

Great idea pointing out if Soon page is blank.

I've added conditional render for the Soon page so a placeholder will appear with a link to git if none exist in the recent commit.

**Comment by nullmames** [comment]
LGTM

**Pull request merged**
