### PR TITLE
Add Fortis Oeconomia to the Juno projects list

### PR DESCRIPTION
**Pull request by IrfanCALISKAN**

### CODE REVIEW

**Comment by blockcreators** [comment]
> _No description provided._

Image size must be 120x120

**Comment by IrfanCALISKAN** [comment]
we updated the image to 120x120

**Comment by blockcreators** [comment]
Your github link just says github.com
Please update when your dapp is launched so we can try it out. Thanks!

**Comment by IrfanCALISKAN** [comment]
We will update github link asap after dapp official launch. Thanks!

**Pull request merged**
