### PR TITLE
Add Junotools beta 

### PR DESCRIPTION
**Pull request by Highlander-maker**

### CODE REVIEW

**Comment by blockcreators** [comment]
> _No description provided._

Image must be 120x120

address field needs smart contract address

**Comment by Highlander-maker** [comment]
just seen this. will change that not today but tomorrow. :)

**Comment by Highlander-maker** [comment]
contract add will add once the code is completed. Will it be ok still to list without this?

**Comment by blockcreators** [comment]
> contract add will add once the code is completed. Will it be ok still to list without this?

Sure

**Pull request merged**
